### https://developer.mozilla.org/en-US/docs/Web/HTTP/Methods/POST

@LangVoyageServer_HostAddress = https://localhost:7231

### Get a noun that I've not practised yet.  This could also return a "learning plan" - right now it assumes nouns
GET {{LangVoyageServer_HostAddress}}/progress/v1/1/noun
Accept: application/json

### Delete all the progress for a user
DELETE {{LangVoyageServer_HostAddress}}/progress/v1/1/noun

### Create/put a NounProgress in place, For nounId = 1
PUT {{LangVoyageServer_HostAddress}}/progress/v1/1/noun/progress
Content-Type: application/json

{
  "NounId": 6,
  "AnswerWasCorrect": true
}


